Cat.create(name: "Luna", age: 1)
Cat.create(name: "Autumn", age: 3)
Cat.create(name: "Granola", age: 7)
Cat.create(name: "Meeko", age: 5)
Cat.create(name: "Lucy", age: 9)
Cat.create(name: "Monkey", age: 12)